### dataset:

**Lens**
```
/data/inspur_disk03/userdir/wangcx/decals_lens/BASS_resolution/grade-A/101t101
/data/inspur_disk03/userdir/wangcx/decals_lens/BASS_resolution/grade-B/101t101
/data/inspur_disk03/userdir/wangcx/decals_lens/BASS_resolution/grade-C/101t101
/data/inspur_disk03/userdir/wangcx/Other_lens_in_decals_BASS_resolution/101t101
```
**non-lens**
```
/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF
/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/COMP 
/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/DEV
/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/REX
```

In [1]:
import astropy.io.fits as fits
import numpy as np
import os
import glob
import matplotlib.pylab as plt

In [2]:
DirBase = "/data/inspur_disk03/userdir/wangcx"

In [3]:
def show(data):
    fig, axes = plt.subplots(1,4,figsize=(4.5*4,4.5))
    ax = axes[0]
    ax.imshow(data[0])
    ax.invert_yaxis()
    ax = axes[1]
    ax.imshow(data[1])
    ax.invert_yaxis()
    ax = axes[2]
    ax.imshow(data[2])
    ax.invert_yaxis()
    ax = axes[3]
    ax.imshow(data.transpose(1,2,0))
    ax.invert_yaxis()

In [4]:
def preprocess(func):
    def wrapper(*args, **kwargs):
        fp = args[0]
        data = func(fp).astype(np.float32)
        cut = 100
        #---------------------------
        m = data.mean(axis=(1,2))[:,None,None]
        s = data.std(axis=(1,2))[:,None,None]
        data -= m
        data /= s
        data = data.transpose(1,2,0)
        #data = np.clip(data,-cut,cut)
        #---------------------------
        return data
    return wrapper

In [5]:
@preprocess
def readdata(fp):
    with fits.open(fp) as hdu:
        data = hdu[0].data
    return data

In [6]:
def readdata2(fp):
    with fits.open(fp) as hdu:
        data = hdu[0].data
    return data

### check old

In [97]:
fp_lensA = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-A/101t101/*.fits'))
fp_lensB = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-B/101t101/*.fits'))
fp_lensC = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-C/101t101/*.fits'))
fp_nlens = glob.glob(os.path.join(DirBase,'decals_non_lens_BASS_resulation/*/cutout*.fits'))

In [98]:
fp_lensA=[i.replace(DirBase+'/','') for i in fp_lensA]
fp_lensB=[i.replace(DirBase+'/','') for i in fp_lensB]
fp_lensC=[i.replace(DirBase+'/','') for i in fp_lensC]
fp_nlens=[i.replace(DirBase+'/','') for i in fp_nlens]

In [99]:
fps = fp_lensA + fp_lensB + fp_lensC + fp_nlens
PATH = []
for fp in fps:
    path = os.path.join(DirBase,fp)
    data = readdata2(path)
    bool0 = data==0.
    if np.all(bool0,axis=(1,2)).any():
        PATH.append(path)

KeyboardInterrupt: 

In [ ]:
PATH

### check 101*101

In [ ]:
fp_lensA = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-A/101t101/cutout*.fits'))
fp_lensB = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-B/101t101/cutout*.fits'))
fp_lensC = glob.glob(os.path.join(DirBase,'decals_lens/BASS_resolution/grade-C/101t101/cutout*.fits'))
fp_nlens = glob.glob(os.path.join(DirBase,'decals_non_lens_BASS_resulation/*/101t101/cutout*.fits'))

In [ ]:
fp_lensA=[i.replace(DirBase+'/','') for i in fp_lensA]
fp_lensB=[i.replace(DirBase+'/','') for i in fp_lensB]
fp_lensC=[i.replace(DirBase+'/','') for i in fp_lensC]
fp_nlens=[i.replace(DirBase+'/','') for i in fp_nlens]

In [ ]:
fps = fp_lensA + fp_lensB + fp_lensC + fp_nlens
PATH = []
for fp in fps:
    path = os.path.join(DirBase,fp)
    data = readdata2(path)
    bool0 = data==0.
    if np.all(bool0,axis=(1,2)).any():
        PATH.append(path)

In [ ]:
PATH

In [ ]:
a = readdata2(PATH[0])

In [ ]:
show(a)

In [ ]:
oa = readdata2('/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF/cutout_127.0432_2.2987.fits')

In [ ]:
show(oa)

In [ ]:
np.all(oa[1,77:178,77:178]==0.)

### training set test

In [ ]:
data = np.load('/data/dell5/userdir/maotx/Lens/data/training.npy')

In [ ]:
image = data['image']

In [ ]:
booln = np.isnan(image).any(axis=(1,2,3))

In [ ]:
print booln.sum()

#### old

In [ ]:
data = np.load('/data/dell5/userdir/maotx/Lens/data_old/training.npy')

In [ ]:
image = data['image']

In [ ]:
booln = np.isnan(image).any(axis=(1,2,3))

In [ ]:
print booln.sum()

In [ ]:
data = np.load('/data/dell5/userdir/maotx/Lens/data_old/test.npy')

In [ ]:
image = data['image']

In [ ]:
booln = np.isnan(image).any(axis=(1,2,3))

In [ ]:
print booln.sum()

In [ ]:
data = np.load('/data/dell5/userdir/maotx/Lens/data_old/valid.npy')

In [ ]:
image = data['image']

In [ ]:
booln = np.isnan(image).any(axis=(1,2,3))

In [ ]:
print booln.sum()

In [ ]:
with open("/data/dell5/userdir/maotx/Lens/data/filename_nlens_tr",'r') as fi:
    filenames = fi.readlines()

In [ ]:
filenames = [i.split('101t101/')[-1][:-1] for i in filenames]

---

In [ ]:
data = np.load('/data/dell5/userdir/maotx/Lens/data_old/training.npy')

### for test

In [ ]:
test_dir_base = '/data/dell5/userdir/maotx/Lens/data'

### for test

In [ ]:
fn_train = np.hstack([FNs[i][0] for i in ['lensA', 'lensB','lensC','nlens']])
nl1 = np.hstack([FNs[i][0] for i in ['lensA', 'lensB','lensC']]).shape[0]
nl0 = np.hstack([FNs[i][0] for i in ['nlens']]).shape[0]
print nl1, nl0
data_tr = np.empty([len(fn_train)], dtype=dt)
data_tr['label'][:nl1]=1
data_tr['label'][nl1:nl1+nl0]=0
remove = []
for i in xrange(len(fn_train)):
    try:
        data_tr['image'][i] = readdata(os.path.join(DirBase,fn_train[i]))
    except ValueError,e:
        data_tr['image'][i] = readdata(os.path.join(DirBase,fn_train[i]))[77:178,77:178,:]
    except AttributeError:
        remove.append(i)
        continue
data_tr = np.delete(data_tr,remove)
print remove

In [ ]:
ss = data['image'][:,0,0,0]

In [ ]:
len(ss), np.unique(ss).shape, 274+17603

In [ ]:
np.isnan(ss).sum()

In [8]:
dt = np.dtype([('label', np.int32, 1), ('image', np.float32, [101,101,3])])

In [12]:
path = ['/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF/cutout_127.0432_2.2987.fits',
 '/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF/cutout_239.7944_1.1127.fits']
data_tr = np.empty([2], dtype=dt)
data_tr['label']=0


for i in xrange(len(path)):
    try:
        data_tr['image'][i] = readdata(path[i])
    except ValueError,e:
        data_tr['image'][i] = readdata(path[i])[77:178,77:178,:]
#    except AttributeError:
#        continue

In [63]:
s = readdata2('/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF/cutout_127.0432_2.2987.fits')
ss = readdata('/data/inspur_disk03/userdir/wangcx/decals_non_lens_BASS_resulation/PSF/cutout_127.0432_2.2987.fits')[77:178,77:178,:]

print np.any(s[0]==0)

True


In [4]:
def preprocess(func):
    def wrapper(*args, **kwargs):
        fp = args[0]
        data = func(fp).astype(np.float32)
        cut = 100
        #---------------------------
        m = data.mean(axis=(1,2))[:,None,None]
        s = data.std(axis=(1,2))[:,None,None]
        data -= m
        data /= s
        data = data.transpose(1,2,0)
        #data = np.clip(data,-cut,cut)
        #---------------------------
        return data
    return wrapper

In [60]:
print ss[:,:,0].mean(),ss[:,:,0].min(),ss[:,:,0].max()

-0.021385195 -0.021385198 -0.021385198


In [64]:
s = s.astype(np.float32)
std = s.std(axis=(1,2))[:,None,None]
mean = s.mean(axis=(1,2))[:,None,None]
print std, mean
s -= mean
s /= std
s = s.transpose(1,2,0)
print s

[[[0.22182262]]

 [[0.35037267]]

 [[0.11469024]]] [[[0.00474372]]

 [[0.00731582]]

 [[0.00547408]]]
[[[ 3.93201411e-03 -2.96581946e-02  9.67664830e-03]
  [-1.91887678e-03 -1.30128618e-02  2.75288612e-01]
  [-2.37886906e-02 -2.64117587e-02 -4.07485992e-01]
  ...
  [-1.07017383e-02 -1.24342870e-02  7.08917389e-03]
  [-9.75589361e-03 -3.18763703e-02 -8.14540759e-02]
  [-5.19861132e-02 -1.95009708e-02 -5.53842857e-02]]

 [[-3.12871411e-02 -4.92690578e-02  6.11210838e-02]
  [ 1.94552355e-02 -2.63010673e-02 -2.17747256e-01]
  [-9.05729365e-03 -1.98204499e-02 -1.49037331e-01]
  ...
  [-3.69265787e-02 -5.56352027e-02 -6.58669919e-02]
  [-1.62454899e-02 -6.83860714e-03 -6.33028597e-02]
  [-3.29924747e-03 -3.89569141e-02 -2.32596740e-01]]

 [[-2.22927239e-02 -3.92352371e-03 -1.42275691e-01]
  [-2.92510632e-02 -1.23122502e-02  9.10894647e-02]
  [ 2.67526843e-02 -6.01387303e-03  1.09063745e-01]
  ...
  [-6.46895841e-02  4.74961847e-03 -2.40510225e-01]
  [-1.03336116e-02 -3.81825306e-02 -2.585558